apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 1323
  - port: 80
    name: low
    protocol: TCP
    targetPort: 1323
